spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./dev.db
    username: sa
    password: 
    generate-unique-name: false
server:
    port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG


whisper:
  storage:
    root: uploads-dev
  email:
    username: haven.orn30@ethereal.email
    password: ZA9treG2f9HC5FSwH6
    host: smtp.ethereal.email
    port: 587
    from: noreply@whisper.com
  client:
    host: http://localhost:5173
  token-type: opaque

