version: '3.3'

services:
  api-gateway-server:
    hostname: api-gateway-server
    image: api-gateway-server:0.0.1
    networks:
      - web-service-network-backend
    expose:
      - 8762
    ports:
      - 8762:8762
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: ["java","-jar","app.jar"]

networks:
  web-service-network-backend: