version: '3.3'
 
services:
  whisper-cache-service:
    hostname: whisper-cache-service
    image: cache-service:0.0.1
    networks:
      - web-service-network-backend
    expose:
      - 9791
    ports:
      - 9791:9791
    environment:
      SPRING_PROFILES_ACTIVE: stage
    entrypoint: ["java","-jar","app.jar"]
 
networks:
  web-service-network-backend: