version: '3.3'
 
services:
  whisper-web-service:
    hostname: whisper-web-service
    image: web-service:0.0.1
    networks:
      - web-service-network-backend
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: stage
    entrypoint: ["java","-jar","app.jar"]
 
networks:
  web-service-network-backend: